### ISSUE TITLE
How to use this nomagic probe?

### ISSUE THREAD

**Issue by kristofmulier** [JustAnother1/nomagic_probe#2]
Hi Lars,

I've flashed your `nomagic_probe` firmware to a `Pi Pico` board. Then, I plug it in and get the following announcement on Windows:

<img src="https://github.com/JustAnother1/nomagic_probe/assets/19362684/7a1bc43f-50ec-46d5-93ba-86d96a51a240" width="400">

So it looks like flashing your firmware to my `Pi Pico` board is a success. However, I don't find any information on how to actually use this board now.

## Hardware connections

As for the hardware side, I believe I should connect my `nomagic_probe` board to a target `Pi Pico` in the following way:

<img src="https://github.com/JustAnother1/nomagic_probe/assets/19362684/0a2d2719-c848-46b1-acca-4050a9098298" width="500">

The `nomagic_probe` would be on the left, the target `Pi Pico` on the right.

Is this correct?

## Software

After making the connections as shown in the figure above, how should I proceed? I tried the following.

I run GDB from the GNU ARM Toolchain. Then I issue a few commands in GDB. This is what I did (PS: I'm on Windows):

```sh
> "C:/Users/krist/EMBEETLE IDE/embeetle/beetle_tools/windows/gnu_arm_toolchain_10.3.1_20210824_32b/bin/arm-none-eabi-gdb"

GNU gdb (GNU Arm Embedded Toolchain 10.3-2021.10) 10.2.90.20210621-git
Copyright (C) 2021 Free Software Foundation, Inc.
[...]

(gdb) file "C:/Users/krist/beetle_projects/rpi-pico/build/application.elf"
Reading symbols from C:/Users/krist/beetle_projects/rpi-pico/build/application.elf...

(gdb) target extended-remote COM11
COM11: No such file or directory.

(gdb) target extended-remote \\.\COM11
Remote debugging using \\.\COM11
Remote communication error.  Target disconnected.: No error.

(gdb) load
You can't do that when your target is `exec'
```

The `nomagic_probe` is connected to `COM11`. I tried to connect to this COM-port, but I get a "Remote communication error".

What should I do?

**Comment by JustAnother1** [comment]
Hi Kristof,

Good that it is working for you. You should be able to see files on the drive.

The firmware is in a very early stage therefore the gdbserver part (as well as many other parts) is not yet working.

I'll update this issue once it makes sense to test gdbserver.

**Comment by kristofmulier** [comment]
Hi Lars
I didn't know the project wasn't ready.

I look forward to see your project evolve. Let me know when it's ready for some testing.

**Comment by JustAnother1** [comment]
Hi Kristof,

Some progress has been made. And some changes were necessary. Therefore I think it was time for an update.

This repository is still the basis for the nomagic probe, but to get a useful binary you need to use one of the new repositories.

The nomagic probe currently runs only on RP2040. So you need a Raspberry Pi pico or similar.  But different target chips (micro controllers that run the firmware you want to debug) will be possible to be used.

If the firmware you want to debug is running on a RP2040 (another Raspberry Pi pico or similar), then this repository should get you started: https://github.com/JustAnother1/rp2040_nomagic_probe

The firmware from that repository will give you a USB serial interface that can be used with gdb like this: `arm-none-eabi-gdb --nh --nx --eval-command="target extended-remote /dev/serial/by-id/usb-Raspberry_Pi_nomagic_probe_000000000001-if00" bin/your_firmware.elf`

A lot of functionality is still missing. I'm working on it. Help is appreciated.

If you want to get a new target chip supported you can start by using the detect repository: https://github.com/JustAnother1/detect_nomagic_probe

That firmware gives you an USB Serial interface (COM Port) with a command line interface. With the provided commands you can check on the new chip and extract the SWD parameters necessary to support a new chip.

The next step would then to set up a new repository similar to the RP2040 one for the new chip. Most functionality/code is in the main repository ( https://github.com/JustAnother1/nomagic_probe ), therefore supporting a new Chip should not be to much effort.

You can report issues either in this repository or in the other two. Please let me know if documentation is missing. Or if you need anything else to get you started.

Kind Regards,

Lars
